"""add fk to payments

Revision ID: cc5a0d8fb482
Revises: 
Create Date: 2025-11-17 09:44:28.432263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc5a0d8fb482'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'ACTIVE', 'DELINQUENT', 'PAID', 'REJECTED', name='creditstatus'), nullable=True),
    sa.Column('monthly_payment', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remaining_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credits_id'), 'credits', ['id'], unique=False)
    op.create_foreign_key(None, 'payment_schedule', 'credits', ['credit_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'credits', ['credit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payment_schedule', type_='foreignkey')
    op.drop_index(op.f('ix_credits_id'), table_name='credits')
    op.drop_table('credits')
    # ### end Alembic commands ###
